import type { CharacterId, CharacterDef, PetState, StateTemplate } from '../types';

export const CHARACTERS: Record<CharacterId, CharacterDef> = {
  blip: {
    label: 'Blip',
    blurb: 'A bouncy little dome of curiosity.',
    palette: { B: '#7BD389', D: '#46A65A', E: '#1F1A1A', M: '#D85A30', C: '#FF9FB0', X: '#FFE066' },
    normal: [
      [
        '..................',
        '.......BBBB.......',
        '......BBBBBB......',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBBBB.',
        '.BBEEBBBBBBBBEEBB.',
        '.BBEEBBBBBBBBEEBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBMMMMBBBBBB.',
        '.BBBBBBMMMMBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBB...BBBB...BBB.',
        '.BB.....BB.....BB.',
        '..................',
      ],
      [
        '..................',
        '.......BBBB.......',
        '......BBBBBB......',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBBBB.',
        '.BBEEBBBBBBBBEEBB.',
        '.BBEEBBBBBBBBEEBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBMMMMBBBBBB.',
        '.BBBBBBMMMMBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BB...BBBBBB...BB.',
        '.B.....BBBB.....B.',
        '..................',
      ],
    ],
    worried: [
      [
        '..................',
        '.......BBBB.......',
        '......BBBBBB......',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBBBB.',
        '.BEEEEBBBBBBEEEEB.',
        '.BEEEEBBBBBBEEEEB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBMMMMBBBBBB.',
        '.BBBBBMBBBBMBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBB...BBBB...BBB.',
        '.BB.....BB.....BB.',
        '..................',
      ],
      [
        '..................',
        '.......BBBB.......',
        '......BBBBBB......',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBBBB.',
        '.BEEEEBBBBBBEEEEB.',
        '.BEEEEBBBBBBEEEEB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBMMMMBBBBBB.',
        '.BBBBBMBBBBMBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '.BB...BBBBBB...BB.',
        '.B.....BBBB.....B.',
        '..................',
      ],
    ],
    sick: [
      [
        '..................',
        '..................',
        '..................',
        '..................',
        '..................',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '..BBMMBBBBBBEEBB..',
        '..BMEEMBBBBBEEBB..',
        '..BBMMBBBBBBBBBB..',
        '..BBBBBBBBBBBBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBBBBBBBBB....',
        '..................',
        '..................',
        '..................',
      ],
      [
        '..................',
        '..................',
        '..................',
        '..................',
        '..................',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '..BMMMBBBBBBEEBB..',
        '..BMEEMBBBBBEEBB..',
        '..BMMMBBBBBBBBBB..',
        '..BBBBBBBBBBBBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBBBBBBBBB....',
        '..................',
        '..................',
        '..................',
      ],
    ],
    dead: [
      [
        '......XXXXXX......',
        '.....XX....XX.....',
        '......XXXXXX......',
        '.......BBBB.......',
        '......BBBBBB......',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBEBEBBBBEBEBB..',
        '..BBBEBBBBBBEBBB..',
        '..BBEBEBBBBEBEBB..',
        '..BBBBBBBBBBBBBB..',
        '..BBBBBBMMMMBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBBBBBBBBB....',
        '....DBDBDBDBDBD...',
        '.....D.D.D.D.D....',
        '..................',
      ],
      [
        '.....XXXXXXXX.....',
        '....XX......XX....',
        '.....XXXXXXXX.....',
        '..................',
        '.......BBBB.......',
        '......BBBBBB......',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBEBEBBBBEBE...',
        '...BBBEBBBBBBEB...',
        '...BBEBEBBBBEBE...',
        '...BBBBBBBBBBBB...',
        '...BBBBMMMMBBBB...',
        '....BBBBBBBBBB....',
        '.....BBBBBBBB.....',
        '.....DBDBDBDB.....',
        '......D.D.D.D.....',
        '..................',
      ],
    ],
  },

  buni: {
    label: 'Buni',
    blurb: 'Twitchy ears, soft heart.',
    palette: { B: '#FFD86B', D: '#D9A82E', E: '#1F1A1A', M: '#8C5A1F', C: '#FFB39B', X: '#FFF' },
    normal: [
      [
        '..................',
        '....BB......BB....',
        '....BB......BB....',
        '....BB......BB....',
        '....BB......BB....',
        '....BBB....BBB....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '..BBEEBBBBBBEEBB..',
        '..BBEEBBBBBBEEBB..',
        '..BBBBBBBBBBBBBB..',
        '..BBBBBBMMBBBBBB..',
        '..BBBBBMMMMBBBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBB....BBB....',
        '..................',
      ],
      [
        '..................',
        '....BB......BB....',
        '....BB......BB....',
        '....BB......BB....',
        '....BB......BB....',
        '....BBB....BBB....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '..BBEEBBBBBBEEBB..',
        '..BBEEBBBBBBEEBB..',
        '..BBBBBBBBBBBBBB..',
        '..BBBBBBMMBBBBBB..',
        '..BBBBMMMMMMBBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BB......BB....',
        '...BBB......BBB...',
      ],
    ],
    worried: [
      [
        '..................',
        '....BB......BB....',
        '....BB......BB....',
        '....BB......BB....',
        '...BB........BB...',
        '...BBB......BBB...',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '..BEEEEBBBBEEEEB..',
        '..BEEEEBBBBEEEEB..',
        '..BBBBBBBBBBBBBB..',
        '..BBBBMMMMMMBBBB..',
        '..BBBMBBBBBBMBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBB....BBB....',
        '..................',
      ],
      [
        '..................',
        '....BB......BB....',
        '....BB......BB....',
        '....BB......BB....',
        '...BB........BB...',
        '...BBB......BBB...',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '..BEEEEBBBBEEEEB..',
        '..BEEEEBBBBEEEEB..',
        '..BBBBBBBBBBBBBB..',
        '..BBBBMMMMMMBBBB..',
        '..BBBMBBBBBBMBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BB......BB....',
        '...BBB......BBB...',
      ],
    ],
    sick: [
      [
        '..................',
        '..................',
        '..................',
        '...BB.............',
        '...BB.............',
        '...BBB............',
        '...BBBBBBBBB......',
        '..BBBBBBBBBBB.....',
        '..BBBBBBBBBBBB....',
        '..BBMMBBBBBEEBB...',
        '..BMEEMBBBBEEBB...',
        '..BBMMBBBBBBBBB...',
        '..BBBBBBBBBBBBB...',
        '..BBBBBBBBBBBB....',
        '...BBBBBBBBBB.....',
        '..................',
        '..................',
        '..................',
      ],
      [
        '..................',
        '..................',
        '..................',
        '...BB.............',
        '...BB.............',
        '...BBB............',
        '...BBBBBBBBB......',
        '..BBBBBBBBBBB.....',
        '..BBBBBBBBBBBB....',
        '..BMMMBBBBBEEBB...',
        '..BMEEMBBBBEEBB...',
        '..BMMMBBBBBBBBB...',
        '..BBBBBBBBBBBBB...',
        '..BBBBBBBBBBBB....',
        '...BBBBBBBBBB.....',
        '..................',
        '..................',
        '..................',
      ],
    ],
    dead: [
      [
        '......XXXXXX......',
        '.....XX....XX.....',
        '......XXXXXX......',
        '....BB......BB....',
        '....BB......BB....',
        '....BBB....BBB....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '..BBEBEBBBBEBEBB..',
        '..BBBEBBBBBBEBBB..',
        '..BBEBEBBBBEBEBB..',
        '..BBBBBBMMBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBBBBBBBBB....',
        '....DBDBDBDBDBD...',
        '.....D.D.D.D.D....',
        '..................',
      ],
      [
        '.....XXXXXXXX.....',
        '....XX......XX....',
        '.....XXXXXXXX.....',
        '....BB......BB....',
        '....BB......BB....',
        '....BBB....BBB....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBEBEBBBBEBEBB..',
        '..BBBEBBBBBBEBBB..',
        '..BBEBEBBBBEBEBB..',
        '..BBBBBBMMBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBBBBBBBBB....',
        '.....BBBBBBBB.....',
        '....DBDBDBDBDB....',
        '.....D.D.D.D.D....',
        '..................',
      ],
    ],
  },

  nova: {
    label: 'Nova',
    blurb: 'Antennae attuned to good vibes.',
    palette: { B: '#C9B3D9', D: '#8472A0', E: '#1F1A1A', M: '#5A3A6A', C: '#FF9FB0', X: '#FFE066' },
    normal: [
      [
        '..................',
        '....B.......B.....',
        '....B.......B.....',
        '....BB.....BB.....',
        '....BBB...BBB.....',
        '.....BB...BB......',
        '...BBBBBBBBBBB....',
        '..BBBBBBBBBBBBB...',
        '.BBBBBBBBBBBBBBB..',
        'BBBEEBBBBBBBEEBBB.',
        'BBBEEBBBBBBBEEBBB.',
        'BBBBBBBBBBBBBBBBB.',
        '.BBBBBBMMBBBBBBB..',
        '.BBBBBBMMBBBBBBB..',
        '..BBBBBBBBBBBBB...',
        '..BBBBBBBBBBBBB...',
        '...BBB....BBB.....',
        '..................',
      ],
      [
        '....B.......B.....',
        '....B.......B.....',
        '....BB.....BB.....',
        '....BBB...BBB.....',
        '.....BB...BB......',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBBB..',
        'BBBEEBBBBBBBEEBBB.',
        'BBBEEBBBBBBBEEBBB.',
        'BBBBBBBBBBBBBBBBB.',
        '.BBBBBBMMBBBBBBB..',
        '.BBBBBBMMBBBBBBB..',
        '..BBBBBBBBBBBBB...',
        '...BBBBBBBBBBB....',
        '....BBB....BBB....',
        '..................',
      ],
    ],
    worried: [
      [
        '..................',
        '....B.......B.....',
        '....B.......B.....',
        '....BB.....BB.....',
        '...BBB.....BBB....',
        '...BB.......BB....',
        '...BBBBBBBBBBB....',
        '..BBBBBBBBBBBBB...',
        '.BBBBBBBBBBBBBBB..',
        'BBEEEEBBBBBEEEEBB.',
        'BBEEEEBBBBBEEEEBB.',
        'BBBBBBBBBBBBBBBBB.',
        '.BBBBMMMMMMMBBBB..',
        '.BBBMBBBBBBBMBBB..',
        '..BBBBBBBBBBBBB...',
        '..BBBBBBBBBBBBB...',
        '...BBB....BBB.....',
        '..................',
      ],
      [
        '..................',
        '....B.......B.....',
        '....B.......B.....',
        '....BB.....BB.....',
        '...BBB.....BBB....',
        '...BB.......BB....',
        '...BBBBBBBBBBB....',
        '..BBBBBBBBBBBBB...',
        '.BBBBBBBBBBBBBBB..',
        'BBEEEEBBBBBEEEEBB.',
        'BBEEEEBBBBBEEEEBB.',
        'BBBBBBBBBBBBBBBBB.',
        '.BBBBMMMMMMMBBBB..',
        '.BBBMBBBBBBBMBBB..',
        '..BBBBBBBBBBBBB...',
        '..BBBBBBBBBBBBB...',
        '...BB......BB.....',
        '..................',
      ],
    ],
    sick: [
      [
        '..................',
        '..................',
        '..................',
        '..................',
        '..................',
        '....B........B....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBBBB.',
        '.BBMMBBBBBBBBEEBB.',
        '.BMEEMBBBBBBBEEBB.',
        '.BBMMBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '..................',
        '..................',
        '..................',
      ],
      [
        '..................',
        '..................',
        '..................',
        '..................',
        '..................',
        '....B........B....',
        '...BBBBBBBBBBBB...',
        '..BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBBBB.',
        '.BMMMBBBBBBBBEEBB.',
        '.BMEEMBBBBBBBEEBB.',
        '.BMMMBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '..................',
        '..................',
        '..................',
      ],
    ],
    dead: [
      [
        '......XXXXXX......',
        '.....XX....XX.....',
        '......XXXXXX......',
        '....B.......B.....',
        '....BB.....BB.....',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBEBEBBBBEBEBB..',
        '..BBBEBBBBBBEBBB..',
        '..BBEBEBBBBEBEBB..',
        '..BBBBBBMMBBBBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBBBBBBBBB....',
        '....DBDBDBDBDBD...',
        '.....D.D.D.D.D....',
        '..................',
      ],
      [
        '.....XXXXXXXX.....',
        '....XX......XX....',
        '.....XXXXXXXX.....',
        '....B.......B.....',
        '....BB.....BB.....',
        '.....BBBBBBBB.....',
        '....BBBBBBBBBB....',
        '...BBBBBBBBBBBB...',
        '..BBEBEBBBBEBEBB..',
        '..BBBEBBBBBBEBBB..',
        '..BBEBEBBBBEBEBB..',
        '..BBBBBBMMBBBBBB..',
        '..BBBBBBBBBBBBBB..',
        '...BBBBBBBBBBBB...',
        '....BBBBBBBBBB....',
        '.....DBDBDBDB.....',
        '......D.D.D.D.....',
        '..................',
      ],
    ],
  },
};

// Shared 8-bit ghost shown for ANY character once the pet is dead (HP=0 for 48h).
// 18x18 to match the other sprites. B = body ink, E = cutout eyes (transparent),
// '.' = empty. Frame B is a 1px bob of frame A.
const GHOST_A: string[] = [
  '..................',
  '......BBBBBB......',
  '....BBBBBBBBBB....',
  '...BBBBBBBBBBBB...',
  '..BBBBBBBBBBBBBB..',
  '..BBBBBBBBBBBBBB..',
  '..BBEEBBBBBBEEBB..',
  '..BBEEBBBBBBEEBB..',
  '..BBBBBBBBBBBBBB..',
  '..BBBBBBBBBBBBBB..',
  '..BBBBBBBBBBBBBB..',
  '..BBBBBBBBBBBBBB..',
  '..BBBBBBBBBBBBBB..',
  '..BBBBBBBBBBBBBB..',
  '..BB..BB..BB..BB..',
  '..................',
  '..................',
  '..................',
];

// Bob: shift down 1 row (drop last, pad top) — keeps every row 18 wide.
const GHOST_B: string[] = ['..................', ...GHOST_A.slice(0, GHOST_A.length - 1)];

export const GHOST_FRAMES: string[][] = [GHOST_A, GHOST_B];

/**
 * Frames for a given character + state. Dead → the shared ghost (ignores the
 * character); every other state → the character's per-template frames.
 */
export function framesFor(
  charDef: CharacterDef,
  state: PetState,
  tmplKey: StateTemplate['tmpl'],
): string[][] {
  if (state === 'dead') return GHOST_FRAMES;
  return charDef[tmplKey] ?? charDef.normal;
}

export const STATE_TO_TEMPLATE: Record<PetState, StateTemplate> = {
  thriving: { tmpl: 'normal', interval: 600 },
  happy: { tmpl: 'normal', interval: 800 },
  neutral: { tmpl: 'normal', interval: 1200 },
  anxious: { tmpl: 'worried', interval: 200 },
  sick: { tmpl: 'sick', interval: 1200 },
  dead: { tmpl: 'dead', interval: 1400 },
};
